### ISSUE TITLE
plug can't enable newly created user account on fedora

### ISSUE THREAD

**Issue by decathorpe** [elementary/switchboard-plug-useraccounts#92] opened 2018-10-30 16:39 UTC
The "Enable User Account" button is active after managing to create a new user, but clicking it does nothing but printing the following message to the logs:

```
(io.elementary.switchboard:2593): accountsservice-WARNING **: 17:38:07.876: SetLocked call failed: GDBus.Error:org.freedesktop.Accounts.Error.Failed: running '/usr/sbin/usermod' failed: Child process exited with code 1
```

**Comment by davidmhewitt** [comment] 2021-10-02 08:54
I couldn't reproduce this issue on Fedora 35, but there were a bunch of other issues that should be resolved once #173, #174 and #175 are merged.

After those are in, I think this plug should be in a pretty good state to be considered for future Fedora releases. I'll close this issue as I can't reproduce it, but feel free to re-open it if you can, or obviously open other issues for other things!

**Closed by davidmhewitt** 2021-10-02 08:54 UTC
