### ISSUE TITLE
Avatars are greyed

### ISSUE THREAD

**Issue by AnaGelez** [elementary/switchboard-plug-useraccounts#121] opened 2019-08-26 19:05 UTC
When setting an avatar from a file, it is greyer than it should be:

![image](https://user-images.githubusercontent.com/16254623/63715874-01341580-c845-11e9-8c67-ba148dd87bb8.png)

(this avatar is the same as the one I have on GitHub for comparison).

It feels like the cropping overlay is still over the image.

And the same "filter" is present in others places too (wingpanel and the greeter).

**Comment by ryonakano** [comment] 2019-08-26 22:38
Possibly a duplicate of https://github.com/elementary/stylesheet/issues/487

**Closed** 2019-08-26 23:31 UTC
Labels: Status: Duplicate
